### PR TITLE
Add Functionality to Print Tasks in Table Format

### PR DESCRIPTION
**Pull request by duressa-feyissa**
**Pull Request Title: Add Functionality to Print Tasks in Table Format**

**Changes proposed in this PR:**
Added a new function printTasksInTableFormat() to the code base.

**Reason for the change:**
The addition of the printTasksInTableFormat() function aims to enhance the Task Manager application by providing a user-friendly and organized way to display tasks in a tabular format. This will improve the overall user experience when viewing tasks and their associated details.

**Details of the change:**
Added a new function printTasksInTableFormat() to the code base, responsible for printing tasks in a table format.
The function iterates through the existing tasks and prints their title, due date, and status in a tabular manner.
If no tasks are found, it displays an informative message indicating that no tasks were found.

**Testing Performed:**
Ran the application locally and tested the printTasksInTableFormat() function with different test cases, including scenarios with empty and non-empty tasks.
Verified that the function prints tasks in a neat table format and displays the correct information for each task.

**Summary / Reviewer's Notes:**
This PR introduces a valuable enhancement to the Task Manager application by adding the printTasksInTableFormat() function. The new function provides a clear and well-organized way to display tasks, making it easier for users to view task details at a glance. The code implementation appears to be straightforward and follows the existing coding style.

As a reviewer, it would be important to ensure that the function handles edge cases, such as empty tasks, and that the table formatting is visually appealing and easy to read. Additionally, the reviewer should assess whether the new function integrates well with the existing code base and does not introduce any unexpected issues.

Please review the changes and feel free to provide any feedback or suggestions for improvement. I am eager to collaborate and make the Task Manager application even better. Thank you for your time and consideration.

Sincerely, Duresa Feyisa

### CODE REVIEW

**Comment by yidyetebeje** [comment]
Code Review for printTableView:

The printTableView method is a member of the Task class. It aims to display details of a task, including its title, description, due date, and status. Let's review this method:

Design and Functionality:

The printTableView() method fulfills its intended functionality of displaying task details to the console.
The method is concise and straightforward, and it achieves its purpose effectively.
Error Handling:

The code doesn't involve any user input or external data, so there are no apparent error handling concerns for this specific method.
Complexity:

The method's complexity is low since it consists of simple print statements to display the task properties.
Naming and Comments:

The method name printTableView() is clear and descriptive, indicating its purpose.
However, it might be helpful to add a comment above the method to explain that this function prints the details of a task.
Consistency:

The method follows the style and conventions used in the existing codebase.
Modularity:

There is no immediate need for modularity in this method, as it is a specific operation for the Task class.
Overall, the printTableView() method appears to be well-designed and effectively accomplishes its task. Consider adding a short comment above the method to clarify its purpose. Apart from that, the method seems to meet the expected standards.

fix:
- there is a bug which shows when the list length zero to prevent that use return statement after the if condition and you don't need the else statement
- 

-

**Review by duressa-feyissa — COMMENTED** [review]
I fix the issue approve for me to merge change into main branch.

**Review by yidyetebeje — COMMENTED** [review]
- fixed

**Comment by duressa-feyissa** [comment]
Thanks for Code Review!

Dear Yidnekachew

Just wanted to say a quick thank you for reviewing my code. Your feedback was extremely helpful, and I appreciate your time and expertise.

Best regards,

**Pull request merged**
